### PR TITLE
Changed the install instructions to also make it run on MacOS. fixes #12

### LINKED ISSUE #12: Can't install on mac os
electron doesn't want to work

And if I run `./node_modules/.bin/electron .`:
photo_2017-01-09_23-30-24

Would also be awesome if you update the instructions afterwards.

_translated by @iamale_

### PR DESCRIPTION
**Pull request by j-holub**
Since I use a Mac anyway I thought I give it a try.

This simple command made it possible to build and run the application on Mac OS. For future releases I'd suggest using the Release functionality of github and provide actual Electron Apps to just download and run.

I did stuff with the CLA-Assistant, I have no idea about it however and how it works and if it works for this pull request. I created a CLA gist and linked it to CLA, maybe it works?

### CODE REVIEW

**Comment by notpushkin** [comment]
Yay, thanks! Strange though, as `pkg.scripts.build` is set to `gulp`, so we just end up running `gulp` twice. Or am I wrong?

@demidovakatya, can you try it too, please? [updated README](https://github.com/00SteinsGate00/desktop/blob/089a54444cc059e172480a79b0812824b370b3a6/README.md)

**Comment by j-holub** [comment]
I have never used gulp before. I installed it for this purpose using `npm install gulp`.
But when I entered `gulp` in the terminal, it said it doesn't know the command (I didn't install it globally). So I had to do `node node_modules/gulp/index.js`.

In the end I didn't use gulp at all and just did

```
npm install
npm run build
npm start
```

The console prompt using `npm run build` was different from all the other output I got.

I'm not proficient with Electron or gulp in anyway, so if my Pull Request ends up being bs, I'm sorry. Just reject it then ^^

**Comment by reo7sp** [comment]
@iamale gulp will be run twice, yes

**Comment by reo7sp** [comment]
I suggest changing install instructions to this:
```sh
npm install gulp-cli -g
npm install
npm run build
npm start
```

**Comment by reo7sp** [comment]
`npm install gulp-cli -g` should fix @demidovakatya's `zsh: command not found: gulp` issue

**Comment by notpushkin** [comment]
@reo7sp :+1::+1::+1::+1:

**Comment by notpushkin** [comment]
@reo7sp With `npm run build` we don't need gulp-cli installed globally, however, as it is already installed in `node_modules/.bin` (with either yarn or npm):

```
$ ls node_modules/.bin
electron  electron-packager  gulp
```

Updated instructions in README to use `[yarn|npm] run build` instead of `gulp`.

**Comment by notpushkin** [comment]
@reo7sp @00SteinsGate00 Thank you, guys!

**Comment by j-holub** [comment]
Glad you could resolve the issue in a nice way :)

**Pull request closed without merging**
